# Generated by Django 2.2.19 on 2022-04-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220412_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(default='none', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='none', max_length=400),
        ),
    ]
