# Generated by Django 2.2.6 on 2022-05-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220507_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='group1',
        ),
    ]
